[project]
name            = 'nya-scope'
dynamic         = ['version']
description     = 'Small helper library for creating named scopes/inline modules'
readme          = "README.md"
requires-python = ">=3.11"
dependencies    = []
license         = "MIT"
license-files   = ["LICENSE"]

# [project.scripts]
# nya_scope = "nya_scope.__main__:main"

classifiers = [ #
	"Development Status :: 5 - Production/Stable",
	"Intended Audience :: Developers",
	"License :: OSI Approved :: MIT License",
	"Operating System :: OS Independent",
	"Programming Language :: Python :: 3",
	"Programming Language :: Python :: 3.11",
	"Programming Language :: Python :: 3.12",
	"Programming Language :: Python :: 3.13",
	"Programming Language :: Python :: 3.14",
	"Programming Language :: Python :: 3.15",
	"Topic :: Software Development :: Libraries",
	"Typing :: Typed",
]

[build-system]
requires      = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path    = "src/nya_scope/_version.py"
pattern = '__version__(?:: str)? *= *\"(?P<version>[^\"]+)\"'

[dependency-groups]
dev = [ #
	"pytest>=9.1.1",
	"rich>=15.0.0",
]
